# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chaeeun Kim
title: PhD student
email: ckim151@ucsc.edu
website: http://chaeeun.me

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  cekim10
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chaeunice_
linkedin_username: chaeeun-kim-a0449013b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: homepage
  icon: fas fa-globe
  url: http://chaeeun.me
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Chaeeun and I'm a 1st year PhD student at UC Santa Cruz. My research interests are Cloud and Edge Computing, Stream processing systems, Large scale graph mining, Distributed algorithm and Distributed systems.

content:
  - title: Publication # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      **Chaeeun Kim**, Changhun Han, and Ha-Myung Park, BTS: Load-Balanced Distributed Union-Find for Finding Connected Components with Balanced Tree Structures, **ICDE 2024** (to appear)
      
      **Chaeeun Kim**, Changhun Han, and Ha-Myung Park, UniCon: A Unified Star-Operation to Efficiently Find Connected Components on a Cluster of Commodity Hardware, **PLOS ONE**, 2022 [[**PDF**](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0277527)][[**source code**](https://github.com/UniCon2021/UniCon)]
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, Santa Cruz
        caption: 2023 - Present
        sub_title: PhD in Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          - Advisor: Liting Hu and Chen Qian
          - Expected graduation date: 2028
          - [**transcript**](https://pdf.ac/30aBPi)
      - layout: left
        title: Kookmin University
        caption: 2020 - 2022
        sub_title: MS in Computer Science
        description: | # this will include new lines to allow paragraphs
          - Advisor: Ha-Myung Park
          - Thesis: An Efficient Algorithm for Computing Connected Components of an Enormous Graph using a Commodity Cluster
      - layout: left
        title: Kookmin University
        caption: 2015 - 2020
        sub_title: BS in Computer Science
        description: | # this will include new lines to allow paragraphs

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Eazel
        link: https://eazel.net/
        sub_title: Data Engineer
        caption: December 2022 - June 2023 
        description: | # this will include new lines to allow paragraphs
          - Crawling art market data (python, socketio, airflow, aws ec2)
          - Building and implementing data pipeline (spark, redshift, msk, kafka, postgresql(aws rds), emr, airflow, s3)
          - Processing data (spark)  
      - layout: left
        title: Toss Securities
        link: https://www.tossinvest.com/
        sub_title: Data Engineer Assistant
        caption: May 2022 - August 2022 
        description: | # this will include new lines to allow paragraphs
          - Developing a data monitoring system (MySQL, Kafka, elasticsearch)
      - layout: left
        title: Humanscape
        link: https://humanscape.io/en/index.html
        sub_title: Software Engineer Intern
        caption: June 2019 - August 2019 
        description: | # this will include new lines to allow paragraphs
          - Developing frontend and backend of mobile applications (Django, React Native)
      - layout: left
        title: ISG Group, UC Irvine
        link: https://cloudberry.ics.uci.edu/
        sub_title: Summer Undergraduate Research Intern
        caption: June 2018 - August 2018 
        description: | # this will include new lines to allow paragraphs
          - Developing frontend of Twittermap service (Python, Angular JS, HTML, CSS)
          - Advisor: Chen Li

  - title: Teaching # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Database systems
        description: | # this will include new lines to allow paragraphs
          - Database systems, Teaching Assistant, Kookmin University (Spring 2021)
      - layout: top-left
        title: Computer Programming
        description: | # this will include new lines to allow paragraphs
          - Computer Programming, Teaching Assistant, Kookmin University (Spring 2020)

  - title: Teaching # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      ACM EuroSys 2024 Travel Grant (April 2024)
  
  - title: Extra Activity # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      Administrator of cluster server (10 machines) in DMlab., Kookmin University (March 2023 - February 2022)
      
      AWS Certified Cloud Practitioner (June 2020)
      
      Coding problem creator for the Coding Competency Certification, Kookmin University (2021)
  

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
